### ISSUE TITLE
Universal distribution strategy (i.e. docker/virtualbox/?)

### ISSUE THREAD

**Issue by diazrenata** [role-model/roleR#68]
So for the workshop we want a pre-installed system of some kind that we can distribute to everyone that will work the same on everyone's laptops. Docker is one way to do this, virtualbox is another. After looking at this for quite a while it seems that both of these methods are confounded by the need to support both intel and arm (new Mac M1/M2) architectures.

* Docker: See my comment below.

* Virtualbox support for M1/M2 chips is [pre-alpha and also broken](https://discussions.apple.com/thread/254763839) (I tried).

**Comment by isaacovercast** [comment]
* [Using docker on apple silicon](https://www.ginkgobioworks.com/2022/07/19/using-docker-on-apple-silicon/) - TLDR; It's not straightforward

**Comment by isaacovercast** [comment]
Virtualization (vbox) doesn't exactly work after all because the underlying architecture is still important. The best way I thought to do this so far was using [UTM on mac](https://docs.getutm.app/) (arm) to run an x86 ubuntu image and then exporting it to .vdi, though this still feels clunky.

Using docker seems more straightforward at the moment and I've got an install idea for containers wired pretty well. See #105 for details on the docker install.

**Comment by ajrominger** [comment]
i think we decided to take the docker plunge right? i'm going to close this, but we can reopen as needed
